openapi: 3.0.0
info:
  version: 2020-06-15
  x-release: v4
  title: 'AWS SSO Identity Store #X Amz Target=AWSIdentityStore.CreateGroup #X Amz Target=AWSIdentityStore.CreateGroup #X Amz Target=AWSIdentityStore.ListGroups API'
  description: <p>The Identity Store service used by AWS IAM Identity Center (successor to AWS Single Sign-On) provides a single place to retrieve all of your identities (users and groups). For more information, see the <a href="https://docs.aws.amazon.com/singlesignon/latest/userguide/what-is.html">IAM Identity Center User Guide</a>.</p> <pre><code> &lt;note&gt; &lt;p&gt;Although AWS Single Sign-On was renamed, the &lt;code&gt;sso&lt;/code&gt; and &lt;code&gt;identitystore&lt;/code&gt; API namespaces will continue to retain their original name for backward compatibility purposes. For more information, see &lt;a href=&quot;https://docs.aws.amazon.com/singlesignon/latest/userguide/what-is.html#renamed&quot;&gt;IAM Identity Center rename&lt;/a&gt;.&lt;/p&gt; &lt;/note&gt; &lt;p&gt;This reference guide describes the identity store operations that you can call programatically and includes detailed information about data types and errors.&lt;/p&gt; </code></pre>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: identitystore
  x-aws-signingName: identitystore
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/identitystore-2020-06-15.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://identitystore.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The IdentityStore multi-region endpoint
- url: https://identitystore.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The IdentityStore multi-region endpoint
- url: http://identitystore.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The IdentityStore endpoint for China (Beijing) and China (Ningxia)
- url: https://identitystore.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The IdentityStore endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=AWSIdentityStore.ListGroups'
paths:
  /#X-Amz-Target=AWSIdentityStore.ListGroups:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListGroups
      description: Lists all groups in the identity store. Returns a paginated list of complete <code>Group</code> objects. Filtering for a <code>Group</code> by the <code>DisplayName</code> attribute is deprecated. Instead, use the <code>GetGroupId</code> API action.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListGroupsResponse'
        '480':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
        '481':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
        '482':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
        '483':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
        '484':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListGroupsRequest'
      parameters:
      - name: MaxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: NextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AWSIdentityStore.ListGroups
      summary: Amazon IAM Identity Center List Groups
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=AWSIdentityStore.ListGroups'
components:
  parameters:
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
  schemas:
    Filters:
      type: array
      items:
        $ref: '#/components/schemas/Filter'
      minItems: 0
      maxItems: 1
    Filter:
      type: object
      required:
      - AttributePath
      - AttributeValue
      properties:
        AttributePath:
          allOf:
          - $ref: '#/components/schemas/AttributePath'
          - description: The attribute path that is used to specify which attribute name to search. Length limit is 255 characters. For example, <code>UserName</code> is a valid attribute path for the <code>ListUsers</code> API, and <code>DisplayName</code> is a valid attribute path for the <code>ListGroups</code> API.
        AttributeValue:
          allOf:
          - $ref: '#/components/schemas/SensitiveStringType'
          - description: 'Represents the data for an attribute. Each attribute value is described as a name-value pair. '
      description: A query filter used by <code>ListUsers</code> and <code>ListGroups</code>. This filter object provides the attribute name and attribute value to search users or groups.
    ListGroupsRequest:
      type: object
      required:
      - IdentityStoreId
      title: ListGroupsRequest
      properties:
        IdentityStoreId:
          allOf:
          - $ref: '#/components/schemas/IdentityStoreId'
          - description: The globally unique identifier for the identity store, such as <code>d-1234567890</code>. In this example, <code>d-</code> is a fixed prefix, and <code>1234567890</code> is a randomly generated string that contains numbers and lower case letters. This value is generated at the time that a new identity store is created.
        MaxResults:
          allOf:
          - $ref: '#/components/schemas/MaxResults'
          - description: The maximum number of results to be returned per request. This parameter is used in the <code>ListUsers</code> and <code>ListGroups</code> requests to specify how many results to return in one page. The length limit is 50 characters.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/NextToken'
          - description: The pagination token used for the <code>ListUsers</code> and <code>ListGroups</code> API operations. This value is generated by the identity store service. It is returned in the API response if the total results are more than the size of one page. This token is also returned when it is used in the API request to search for the next page.
        Filters:
          allOf:
          - $ref: '#/components/schemas/Filters'
          - deprecated: true
            description: A list of <code>Filter</code> objects, which is used in the <code>ListUsers</code> and <code>ListGroups</code> requests.Using filters with ListGroups API is deprecated, please use GetGroupId API instead.
    ExternalIdIdentifier:
      type: string
      pattern: '[\p{L}\p{M}\p{S}\p{N}\p{P}]+'
      minLength: 1
      maxLength: 256
      format: password
    ExternalId:
      type: object
      required:
      - Issuer
      - Id
      properties:
        Issuer:
          allOf:
          - $ref: '#/components/schemas/ExternalIdIssuer'
          - description: The issuer for an external identifier.
        Id:
          allOf:
          - $ref: '#/components/schemas/ExternalIdIdentifier'
          - description: The identifier issued to this resource by an external identity provider.
      description: The identifier issued to this resource by an external identity provider.
    Groups:
      type: array
      items:
        $ref: '#/components/schemas/Group'
    NextToken:
      type: string
      pattern: '[-a-zA-Z0-9+=/:]*'
      minLength: 1
      maxLength: 65535
    AccessDeniedException: {}
    ExternalIds:
      type: array
      items:
        $ref: '#/components/schemas/ExternalId'
      minItems: 1
      maxItems: 10
    ResourceNotFoundException: {}
    ListGroupsResponse:
      type: object
      required:
      - Groups
      properties:
        Groups:
          allOf:
          - $ref: '#/components/schemas/Groups'
          - description: A list of <code>Group</code> objects in the identity store.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/NextToken'
          - description: The pagination token used for the <code>ListUsers</code> and <code>ListGroups</code> API operations. This value is generated by the identity store service. It is returned in the API response if the total results are more than the size of one page. This token is also returned when it1 is used in the API request to search for the next page.
    ResourceId:
      type: string
      pattern: ([0-9a-f]{10}-|)[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}
      minLength: 1
      maxLength: 47
    ExternalIdIssuer:
      type: string
      pattern: \(\?!\(\?i\)\(arn\|aws\):\)[\p\{L\}\p\{M\}\p\{S\}\p\{N\}\p\{P\}]\+
      minLength: 1
      maxLength: 100
      format: password
    AttributePath:
      type: string
      pattern: \p{L}+(?:\.\p{L}+){0,2}
      minLength: 1
      maxLength: 255
    SensitiveStringType:
      type: string
      pattern: '[\p{L}\p{M}\p{S}\p{N}\p{P}\t\n\r  　]+'
      minLength: 1
      maxLength: 1024
      format: password
    ThrottlingException: {}
    ValidationException: {}
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    IdentityStoreId:
      type: string
      pattern: d-[0-9a-f]{10}$|^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}
      minLength: 1
      maxLength: 36
    Group:
      type: object
      required:
      - GroupId
      - IdentityStoreId
      properties:
        GroupId:
          allOf:
          - $ref: '#/components/schemas/ResourceId'
          - description: The identifier for a group in the identity store.
        DisplayName:
          allOf:
          - $ref: '#/components/schemas/GroupDisplayName'
          - description: The display name value for the group. The length limit is 1,024 characters. This value can consist of letters, accented characters, symbols, numbers, punctuation, tab, new line, carriage return, space, and nonbreaking space in this attribute. This value is specified at the time the group is created and stored as an attribute of the group object in the identity store.
        ExternalIds:
          allOf:
          - $ref: '#/components/schemas/ExternalIds'
          - description: A list of <code>ExternalId</code> objects that contains the identifiers issued to this resource by an external identity provider.
        Description:
          allOf:
          - $ref: '#/components/schemas/SensitiveStringType'
          - description: A string containing a description of the specified group.
        IdentityStoreId:
          allOf:
          - $ref: '#/components/schemas/IdentityStoreId'
          - description: The globally unique identifier for the identity store.
      description: A group object that contains the metadata and attributes for a specified group.
    InternalServerException: {}
    GroupDisplayName:
      type: string
      pattern: '[\p{L}\p{M}\p{S}\p{N}\p{P}\t\n\r  ]+'
      minLength: 1
      maxLength: 1024
      format: password
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/identitystore/
x-hasEquivalentPaths: true
